Db department
infoshareacademy/jfdzr13-team-lospollos pull request #12
Opened 2024-06-10 19:12 UTC by PawelJazdzyk

1. Add DepartmentService
2. Add DepartmentService to ViewDataContext
3. Add DepartmentFinder function - working on AddRequest component
4. Renamed some files

2024-06-12 19:57 UTC, andrzejpalica requested changes

2024-06-12 19:57 UTC, andrzejpalica commented on los-urlopos/src/utils/DepartmentFinder.ts
> +}
1. tu mozna zrobic to duzo prosciej przez metode filter na kolekcji deptList
2. pytanie czy jest sens w takim razie tworzyc funkcje pomocnicza, skoro mozemy to sobie w prosty sposob zrobic w bezposrednio w komponencie
3. nazwa tego parametr user ktory stworzyles w linii 1 ma sie zupelnie nijak do jego faktycznej wartosci czyli deptId z usera. przez 30 min sie zastanawialem dlaczego pchasz usera do wyszukiwania userow skoro  w departametach nie mamy nic zwiazanego z userami :)

2024-06-12 19:57 UTC, andrzejpalica commented on los-urlopos/src/components/AddRequest/AddRequest.tsx
> +      dept: departments.dept,
w bazie musimy trzymac departmentid zeby mozna bylo potem filtrowac request dla danego departametnu. takze tutaj powinno byc deptartmentId wysylane do requestu.

2024-06-12 19:57 UTC, andrzejpalica commented on los-urlopos/src/components/AddRequest/AddRequest.tsx
> +      supervisor: departments.head,
request o urlop powinien byc przypisany do departamentu a nie to supervisora. rozmawialismy o tym na zajeciach.

2024-06-13 18:45 UTC, andrzejpalica approved these changes

2024-06-15 05:30 UTC, kasz91 approved these changes
I feel it works :)

2024-06-15 05:30 UTC, merged