admin panel part 1
infoshareacademy/jfdzr13-team-lospollos pull request #36
Opened 2024-06-23 12:13 UTC by platek92

1. moved auth logic to AuthService
2. created separate components for different admin actions
3. initial password is now deifned by Admin
4. createdBy is now filled automatically
5. double check is now on when deleting user
6. Add user is now pop up Modal

2024-06-23 17:45 UTC, andrzejpalica requested changes

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/components/AdminPanel/AddUser/AddUser.tsx
> +      });
to powinno byc przeniesione do UserService.ts gdzie trzymamy wszystkie metody sluzace do komunikacji z firebase

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/components/AdminPanel/AddUser/AddUser.tsx
> +        }));
tego nie musimy tu pobierac poniewaz trzymamy to w ViewDataContext jako UserData. context Usera jest pobierany przy logowaniu.

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/services/AuthService.ts
> +  const auth = getAuth();
to juz mamy w firebase.ts i nawet jest tutaj zaimportowane w linii 6

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/contexts/ViewDataContext.tsx
> +  const [userData, setUserData] = useState<User[]>([]);
tu chyba chcemy zostac przy nullu, bo to domyslnie przechwouje dane jednego usera ktory obecnie jest zalogowowny, lub nic jak nie jest zalogowany/wyloguje sie.

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/components/AdminPanel/UsersList/UsersList.tsx
> +      }
to powinno byc dodane do UserService jako metoda getAllUsers

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/components/AdminPanel/UsersList/UsersList.tsx
> +  };
tu tak samo jako powinno byc w UserService jako deleteUserById()

2024-06-23 17:45 UTC, andrzejpalica commented on los-urlopos/src/components/AdminPanel/AddUser/AddUser.tsx
> +    }
ogolnie sie zastanawiam dlaczego w metodzie addUser nie pobierzemy po prostu wartosci z pol z formularza do tworzenia nowego usera, a nastepnie nie stworzymy nowego obiektu User, gdzie podstawimy te wartosci z formularaza i potem tego usera wyslemy do bazy. wtedy nie trzeba by bylo w ogole tworzyc tych stanow User i Password.

2024-06-24 17:37 UTC, platek92 commented on los-urlopos/src/services/AuthService.ts
> +  const auth = getAuth();
ok, fakt

2024-06-24 18:35 UTC, platek92 commented on los-urlopos/src/contexts/ViewDataContext.tsx
> +  const [userData, setUserData] = useState<User[]>([]);
ok ale to nie dzialalo wczesniej :)

2024-06-24 20:59 UTC, platek92 commented on los-urlopos/src/components/AdminPanel/UsersList/UsersList.tsx
> +      }
ok

2024-06-24 20:59 UTC, platek92 commented on los-urlopos/src/components/AdminPanel/UsersList/UsersList.tsx
> +  };
ok

2024-06-24 21:27 UTC, platek92 commented on los-urlopos/src/components/AdminPanel/AddUser/AddUser.tsx
> +      });
gotowe, chociaz czesciowo bo nie chcialem usuwac juz wnetrza, zrzucilem tylko db

2024-06-24 21:36 UTC, platek92 commented on los-urlopos/src/components/AdminPanel/AddUser/AddUser.tsx
> +        }));
musze powiedzieć że nie wiem jak wykorzystać dane z contextu z UserData, tutaj pobieram to tylko aby automatycznie przyspiac createdBy - mozesz zaproponować jak ma to wyglądać? thx

2024-06-25 00:08 UTC, andrzejpalica approved these changes

2024-06-25 00:08 UTC, andrzejpalica commented on los-urlopos/src/contexts/ViewDataContext.tsx
> +  const [userData, setUserData] = useState<User[]>([]);
ja wciaz nie jestem przekonany do tej zmiany. bo w tym stanie trzymamy Usera wiec ten typ z tablica usera i pusta tablica w inicjalnym stanie stanu mi sie nie widzi. ale poki u Ciebie to dziala i aplikacja to jakos ogarnia to pojdzmy z tym. ale ja jeszcze poszukam w wolnym czasie dlaczego ta zmiana rozwiazuje ten Twoj problem.

2024-06-25 04:33 UTC, PawelJazdzyk approved these changes

2024-06-28 10:13 UTC, merged