validations and some little changes
infoshareacademy/jfdzr13-team-lospollos pull request #77
Opened 2024-07-06 15:02 UTC by PawelJazdzyk

- add validation to add user  in admin panel (number of On Demand Days)
- change default sorting on table for FROM column

2024-07-06 16:15 UTC, kasz91 approved these changes

2024-07-06 19:12 UTC, kasz91 approved these changes

2024-07-06 19:12 UTC, kasz91 commented on los-urlopos/src/components/SupervisorPanel/SupervisorComponent/SpvComponent.tsx
> +        <h4>{userView.email}</h4>
Nie wiem czy jest to sens zmieniać w ten sposób,
rozjechało się to ponieważ w 'poprawkach' stylowania został zwiększony jakiś globalny fontSize...
Wyciagnięcie tego z diva spowoduje brak spójności tych elementów które miały stanowić blok.
Powinno to być naprawione tym czym zostało zmienione.

2024-07-06 19:12 UTC, kasz91 commented on los-urlopos/src/components/UserPanel/UserComponent/UserComponent.tsx
> +        <h4>{userView.email}</h4>
To samo co wyżej.

2024-07-06 21:36 UTC, andrzejpalica requested changes

2024-07-06 21:36 UTC, andrzejpalica commented on los-urlopos/src/components/SupervisorPanel/SupervisorComponent/SpvComponent.tsx
> +        <h4>{userView.email}</h4>
zgadza sie, tam wszedl bug ze stylowaniem h2 na cala aplikacje zamiast na liste departmentow tylko, juz zrobilem na to fixa i wszystko wrocilo do normy

2024-07-06 21:36 UTC, andrzejpalica commented on los-urlopos/src/components/UserPanel/UserComponent/UserComponent.tsx
> +        <h4>{userView.email}</h4>
jak wyzej

2024-07-07 06:13 UTC, andrzejpalica approved these changes

2024-07-07 06:14 UTC, merged