supervisor request table update
infoshareacademy/jfdzr13-team-lospollos pull request #79
Opened 2024-07-06 19:59 UTC by kasz91

+ service for Employee's Name firstName+surname
+ change paging in userRT bsc catch error in console
+ remove 'y' form adminUT

2024-07-06 21:52 UTC, andrzejpalica requested changes

2024-07-06 21:52 UTC, andrzejpalica commented on los-urlopos/src/components/SupervisorPanel/SpvRequestsTable/SpvRequestsTable.tsx
> +              }, [userId]);
nie jestem pewien, ale tu moze byc znowu ogien. w lini 173 ustawiany userId a potem w 192 uzalezniamy wywolanie usEffecta od tego userId

2024-07-06 21:58 UTC, andrzejpalica commented on los-urlopos/src/components/SupervisorPanel/SpvRequestsTable/SpvRequestsTable.tsx
> +              }, [userId]);
choc teraz w sumie widze, ze to ustawienie userId jest poza useEffectem takze wyglada jednak ok. wywola sie tyle razy ile jest userow na liscie, ale inaczej tego nie zrobimy. daje jednak approvala xd

2024-07-06 21:58 UTC, andrzejpalica approved these changes

2024-07-07 05:53 UTC, kasz91 reviewed
Changes updated,
deleted useEffect drom Cell renderer

2024-07-07 06:12 UTC, PawelJazdzyk approved these changes

2024-07-07 06:15 UTC, andrzejpalica approved these changes

2024-07-07 06:15 UTC, merged